Feature/APP-3120_payment_method_selection_second_screen
Catappult/appcoins-sdk-ios pull request #45
Opened 2024-11-28 10:50 UTC by Gracian0-Caldeir4

**What does this PR do?**

   This PR adds a dedicated view for browsing and selecting payment methods, enhancing the payment experience by providing users with a focused interface. Upon selecting a payment method, users are seamlessly redirected back to the main payment screen with their choice pre-selected, aligning with best practices for clarity and ease of use in the payment process. 

**Database changed?**

   No

**Where should the reviewer start?**

- [ ] BottomSheetView.swift
- [ ] PurchaseBottomSheet.swift
- [ ] SelectedPaymentMethodView.swift
- [ ] PaymentMethodChoiceView.swift
- [ ] BottomSheetViewModel.swift

**How should this be manually tested?**

  Run the Trivial Drive feature and tap on the “Select Payment Method” button. Choose a payment method and verify that the flow correctly returns to the main bottom sheet with the selected payment method pre-selected.

**What are the relevant tickets?**

  Tickets related to this pull-request: APP-3120

**Questions:**

   Does this add new dependencies which need to be added? (Eg. new keys, etc.) 

**Code Review Checklist**

- [ ] Documentation on public interfaces
- [ ] Database changed? If yes - Migration?
- [ ] Remove comments & unused code & forgotten testing Logs
- [ ] Codestyle
- [ ] New Kotlin code has unit tests
- [ ] New flows in presenters unit tests
- [ ] Mappers/Validators with any kind of logic unit tests
- [ ] Functional tests pass

2024-12-09 16:07 UTC, tiaguu requested changes
Overall, it is quite good. Just some matters regarding variable naming that need to be adjusted.

2024-12-09 16:26 UTC, Gracian0-Caldeir4 commented on Sources/AppCoinsSDK/Localization/Localizable.xcstrings
> +    "chevron.right" : {
Done

2024-12-09 16:41 UTC, Gracian0-Caldeir4 commented on Sources/AppCoinsSDK/UI/Purchase/ViewModels/BottomSheetViewModel.swift
> +    @Published var canChooseMethod: Bool = false
Done

2024-12-09 16:41 UTC, Gracian0-Caldeir4 commented on Sources/AppCoinsSDK/UI/Purchase/ViewModels/BottomSheetViewModel.swift
> +    internal func setCanChooseMethod(canChooseMethod: Bool) {
Done

2024-12-09 16:46 UTC, Gracian0-Caldeir4 commented on Sources/AppCoinsSDK/Utils/Constants.swift
> +    static internal let signToGetBonusText = NSLocalizedString("sign_to_get_bonus_button", bundle: .APPCModule, comment: "Sign in to get your bonus")
Done

2024-12-10 10:46 UTC, Gracian0-Caldeir4 commented on Sources/AppCoinsSDK/UI/Purchase/Cells/PaymentMethodList.swift
> +                        if viewModel.canChooseMethod == true {
Done

2024-12-10 11:00 UTC, Gracian0-Caldeir4 commented on Sources/AppCoinsSDK/UI/Purchase/ViewModels/BottomSheetViewModel.swift
> +    @Published var didLogin: Bool = false
Done

2024-12-10 11:00 UTC, Gracian0-Caldeir4 commented on Sources/AppCoinsSDK/UI/Purchase/PurchaseStateViews/PaymentMethodChoiceView.swift
> +struct PaymentMethodChoiceView: View {
Done

2024-12-10 15:26 UTC, merged